import { kelvinToHsl, type HSL } from './color.ts'
import { defaultLook, type Anim, type Look, type Mode } from './look.ts'

export type PresetCategory = 'call' | 'white' | 'scene' | 'tool'

export type Preset = {
  id: string
  name: string
  blurb: string
  category: PresetCategory
  look: Partial<Look>
}

const k = (kelvin: number): HSL => kelvinToHsl(kelvin)

export const CATEGORIES: { id: PresetCategory; label: string }[] = [
  { id: 'call', label: 'Videollamada' },
  { id: 'white', label: 'Blancos' },
  { id: 'scene', label: 'Escenas' },
  { id: 'tool', label: 'Utilidad' },
]

export const PRESETS: Preset[] = [
  {
    id: 'key-warm',
    name: 'Key cálida',
    blurb: 'Luz principal para cara, 3200K',
    category: 'call',
    look: {
      mode: 'kelvin',
      kelvin: 3200,
      brightness: 0.94,
      vignette: 0.28,
      grain: 0.05,
      anim: 'none',
      warmShift: 0.08,
    },
  },
  {
    id: 'beauty',
    name: 'Beauty',
    blurb: 'Rosa suave que favorece piel',
    category: 'call',
    look: {
      mode: 'solid',
      color: { h: 12, s: 42, l: 74 },
      brightness: 0.96,
      vignette: 0.22,
      grain: 0.04,
      anim: 'none',
    },
  },
  {
    id: 'office',
    name: 'Oficina',
    blurb: 'Neutro de escritorio, 4100K',
    category: 'call',
    look: {
      mode: 'kelvin',
      kelvin: 4100,
      brightness: 0.9,
      vignette: 0.12,
      grain: 0.03,
      anim: 'none',
    },
  },
  {
    id: 'fill-cool',
    name: 'Fill frío',
    blurb: 'Rellena sombras sin aplastar',
    category: 'call',
    look: {
      mode: 'kelvin',
      kelvin: 5600,
      brightness: 0.78,
      vignette: 0.16,
      grain: 0.04,
      anim: 'none',
    },
  },
  {
    id: 'ring',
    name: 'Ring light',
    blurb: 'Blanco alto, viñeta de aro',
    category: 'call',
    look: {
      mode: 'gradient',
      gradKind: 'radial',
      gradA: { h: 32, s: 18, l: 94 },
      gradB: { h: 28, s: 28, l: 62 },
      brightness: 1,
      vignette: 0.42,
      grain: 0.02,
      anim: 'none',
    },
  },
  {
    id: 'night-stream',
    name: 'Stream noche',
    blurb: 'Ámbar bajo, no ciega al cuarto',
    category: 'call',
    look: {
      mode: 'solid',
      color: { h: 28, s: 78, l: 48 },
      brightness: 0.62,
      vignette: 0.36,
      grain: 0.1,
      anim: 'breathe',
      animSpeed: 0.7,
    },
  },
  {
    id: 'podcast',
    name: 'Podcast',
    blurb: 'Cálido íntimo para voz y cara',
    category: 'call',
    look: {
      mode: 'solid',
      color: { h: 24, s: 64, l: 58 },
      brightness: 0.86,
      vignette: 0.3,
      grain: 0.07,
      anim: 'none',
    },
  },
  {
    id: 'interview',
    name: 'Entrevista',
    blurb: 'Día limpio, 5600K plano',
    category: 'call',
    look: {
      mode: 'kelvin',
      kelvin: 5600,
      brightness: 0.95,
      vignette: 0.1,
      grain: 0.02,
      anim: 'none',
    },
  },
  {
    id: 'k-1900',
    name: 'Vela',
    blurb: '1900K, parpadeo suave',
    category: 'white',
    look: {
      mode: 'kelvin',
      kelvin: 1900,
      brightness: 0.55,
      vignette: 0.4,
      grain: 0.12,
      anim: 'flicker',
      animSpeed: 1.1,
    },
  },
  {
    id: 'k-2700',
    name: 'Tungsteno',
    blurb: '2700K living',
    category: 'white',
    look: { mode: 'kelvin', kelvin: 2700, brightness: 0.88, vignette: 0.2, grain: 0.05, anim: 'none' },
  },
  {
    id: 'k-3000',
    name: 'Soft white',
    blurb: '3000K lámpara buena',
    category: 'white',
    look: { mode: 'kelvin', kelvin: 3000, brightness: 0.9, vignette: 0.16, grain: 0.04, anim: 'none' },
  },
  {
    id: 'k-4000',
    name: 'Neutral',
    blurb: '4000K cocina / lab',
    category: 'white',
    look: { mode: 'kelvin', kelvin: 4000, brightness: 0.92, vignette: 0.1, grain: 0.03, anim: 'none' },
  },
  {
    id: 'k-5600',
    name: 'Día',
    blurb: '5600K foto y video',
    category: 'white',
    look: { mode: 'kelvin', kelvin: 5600, brightness: 1, vignette: 0.08, grain: 0.02, anim: 'none' },
  },
  {
    id: 'k-6500',
    name: 'Nublado',
    blurb: '6500K cielo cubierto',
    category: 'white',
    look: { mode: 'kelvin', kelvin: 6500, brightness: 0.96, vignette: 0.08, grain: 0.02, anim: 'none' },
  },
  {
    id: 'sunset',
    name: 'Atardecer',
    blurb: 'Durazno a magenta',
    category: 'scene',
    look: {
      mode: 'gradient',
      gradKind: 'linear',
      angle: 168,
      gradA: { h: 18, s: 86, l: 62 },
      gradB: { h: 328, s: 62, l: 38 },
      brightness: 0.86,
      vignette: 0.2,
      grain: 0.08,
      anim: 'none',
    },
  },
  {
    id: 'ocean',
    name: 'Océano',
    blurb: 'Teal profundo',
    category: 'scene',
    look: {
      mode: 'gradient',
      gradKind: 'linear',
      angle: 200,
      gradA: { h: 186, s: 58, l: 52 },
      gradB: { h: 212, s: 64, l: 28 },
      brightness: 0.8,
      vignette: 0.24,
      grain: 0.06,
      anim: 'breathe',
      animSpeed: 0.85,
    },
  },
  {
    id: 'forest',
    name: 'Bosque',
    blurb: 'Verde musgo',
    category: 'scene',
    look: {
      mode: 'solid',
      color: { h: 142, s: 32, l: 32 },
      brightness: 0.72,
      vignette: 0.34,
      grain: 0.1,
      anim: 'none',
    },
  },
  {
    id: 'neon',
    name: 'Neón',
    blurb: 'Magenta de club',
    category: 'scene',
    look: {
      mode: 'solid',
      color: { h: 318, s: 86, l: 54 },
      brightness: 0.88,
      vignette: 0.18,
      grain: 0.04,
      anim: 'pulse',
      animSpeed: 1.15,
    },
  },
  {
    id: 'lavender',
    name: 'Lavanda',
    blurb: 'Dusk violeta',
    category: 'scene',
    look: {
      mode: 'solid',
      color: { h: 268, s: 36, l: 62 },
      brightness: 0.82,
      vignette: 0.22,
      grain: 0.06,
      anim: 'none',
    },
  },
  {
    id: 'ember',
    name: 'Ember',
    blurb: 'Brasa viva',
    category: 'scene',
    look: {
      mode: 'gradient',
      gradKind: 'radial',
      gradA: { h: 28, s: 92, l: 56 },
      gradB: { h: 8, s: 78, l: 22 },
      brightness: 0.74,
      vignette: 0.38,
      grain: 0.12,
      anim: 'flicker',
      animSpeed: 0.9,
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    blurb: 'Verde y violeta en deriva',
    category: 'scene',
    look: {
      mode: 'gradient',
      gradKind: 'linear',
      angle: 122,
      gradA: { h: 164, s: 58, l: 48 },
      gradB: { h: 278, s: 52, l: 42 },
      brightness: 0.78,
      vignette: 0.2,
      grain: 0.08,
      anim: 'aurora',
      animSpeed: 1,
    },
  },
  {
    id: 'champagne',
    name: 'Champagne',
    blurb: 'Dorado de fiesta',
    category: 'scene',
    look: {
      mode: 'solid',
      color: { h: 42, s: 58, l: 68 },
      brightness: 0.9,
      vignette: 0.16,
      grain: 0.05,
      anim: 'none',
    },
  },
  {
    id: 'wine',
    name: 'Vino',
    blurb: 'Borgoña denso',
    category: 'scene',
    look: {
      mode: 'solid',
      color: { h: 348, s: 48, l: 28 },
      brightness: 0.7,
      vignette: 0.32,
      grain: 0.1,
      anim: 'none',
    },
  },
  {
    id: 'spa',
    name: 'Spa',
    blurb: 'Menta de agua',
    category: 'scene',
    look: {
      mode: 'solid',
      color: { h: 166, s: 28, l: 72 },
      brightness: 0.88,
      vignette: 0.14,
      grain: 0.04,
      anim: 'breathe',
      animSpeed: 0.6,
    },
  },
  {
    id: 'darkroom',
    name: 'Cuarto oscuro',
    blurb: 'Rojo safelight',
    category: 'tool',
    look: {
      mode: 'solid',
      color: { h: 4, s: 86, l: 34 },
      brightness: 0.48,
      vignette: 0.2,
      grain: 0.06,
      anim: 'none',
    },
  },
  {
    id: 'focus-blue',
    name: 'Foco azul',
    blurb: 'Concentración fría',
    category: 'tool',
    look: {
      mode: 'solid',
      color: { h: 218, s: 48, l: 42 },
      brightness: 0.7,
      vignette: 0.26,
      grain: 0.05,
      anim: 'none',
    },
  },
  {
    id: 'sleep',
    name: 'Sleep',
    blurb: 'Ámbar sin azul',
    category: 'tool',
    look: {
      mode: 'solid',
      color: { h: 26, s: 88, l: 42 },
      brightness: 0.38,
      vignette: 0.48,
      grain: 0.08,
      anim: 'breathe',
      animSpeed: 0.45,
    },
  },
  {
    id: 'photo',
    name: 'Foto',
    blurb: 'Blanco plano para disparar',
    category: 'tool',
    look: {
      mode: 'solid',
      color: { h: 40, s: 4, l: 96 },
      brightness: 1,
      vignette: 0,
      grain: 0,
      anim: 'none',
    },
  },
  {
    id: 'blackout',
    name: 'Apagado',
    blurb: 'Negro mate',
    category: 'tool',
    look: {
      mode: 'solid',
      color: { h: 0, s: 0, l: 2 },
      brightness: 1,
      vignette: 0,
      grain: 0,
      anim: 'none',
    },
  },
  {
    id: 'split-warm-cool',
    name: 'Warm / Cool',
    blurb: 'Split para dos lados',
    category: 'tool',
    look: {
      mode: 'split',
      splitAxis: 'v',
      splitRatio: 0.5,
      splitA: k(2900),
      splitB: k(6200),
      brightness: 0.9,
      vignette: 0.08,
      grain: 0.03,
      anim: 'none',
    },
  },
]

export const QUICK: { name: string; color: HSL; mode?: Mode; kelvin?: number; anim?: Anim }[] = [
  { name: 'Cálida', color: { h: 24, s: 70, l: 60 } },
  { name: 'Peach', color: { h: 16, s: 72, l: 70 } },
  { name: 'Beauty', color: { h: 10, s: 40, l: 76 } },
  { name: 'Día', color: kelvinToHsl(5600) },
  { name: 'Cool', color: kelvinToHsl(6500) },
  { name: 'Menta', color: { h: 166, s: 32, l: 62 } },
  { name: 'Bosque', color: { h: 142, s: 30, l: 34 } },
  { name: 'Océano', color: { h: 200, s: 52, l: 42 } },
  { name: 'Violeta', color: { h: 272, s: 40, l: 52 } },
  { name: 'Neón', color: { h: 318, s: 84, l: 54 } },
  { name: 'Ember', color: { h: 18, s: 86, l: 48 } },
  { name: 'Apagado', color: { h: 0, s: 0, l: 2 } },
]

export function applyPreset(current: Look, preset: Preset): Look {
  return {
    ...defaultLook(),
    ...current,
    ...preset.look,
    color: preset.look.color ?? current.color,
    mix: preset.look.mix ?? current.mix,
    mixWeights: preset.look.mixWeights ?? current.mixWeights,
    gradA: preset.look.gradA ?? current.gradA,
    gradB: preset.look.gradB ?? current.gradB,
    splitA: preset.look.splitA ?? current.splitA,
    splitB: preset.look.splitB ?? current.splitB,
  }
}
